In [7]:
"""
Cree una matriz de 7 columnas por 9 filas. Las primeras 3 columnas de la matriz tienen que 
tener el valor 0. La cuarta columna debe tener el valor 0.5, excepto por el último valor de 
esa columna, que tiene que ser 0.7. Las otras tres columnas deben tener el valor 1.
Imprima la matriz y calcule las suma de los elementos de la última fila
"""
import numpy as np
m = np.zeros([9,7])
print(m)
a=[0.5]
a=a*8
a.append(0.7)
print(a)

for i in range(0,9):
    m[i,3] = a[i]
    for j in range(4,7):
        m[i,j] = 1
print(m)
mx = np.ones([7,3])
print(mx)
# Suma de los elementos de la última fila
print("Suma de la última fila : ", np.sum(m,axis=1)[8])

"""
La siguiente instrucción crea una matriz aleatoria de 5 por 5 con valores entre 0 y 1 
matriz_aleatoria=np.random.rand(5,5)
Imprima las posiciones (Fila y columna) de los elementos de la matriz que son mayores que 0.5
"""

matriz_aleatoria=np.random.rand(5,5)
print(matriz_aleatoria)
mascara = matriz_aleatoria > 0.5
print(mascara)
for fila in range(0,5):
    for columna in range(0,5):
        if(mascara[fila,columna]): print(fila,columna)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.7]
[[ 0.   0.   0.   0.5  1.   1.   1. ]
 [ 0.   0.   0.   0.5  1.   1.   1. ]
 [ 0.   0.   0.   0.5  1.   1.   1. ]
 [ 0.   0.   0.   0.5  1.   1.   1. ]
 [ 0.   0.   0.   0.5  1.   1.   1. ]
 [ 0.   0.   0.   0.5  1.   1.   1. ]
 [ 0.   0.   0.   0.5  1.   1.   1. ]
 [ 0.   0.   0.   0.5  1.   1.   1. ]
 [ 0.   0.   0.   0.7  1.   1.   1. ]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
Suma de la última fila :  3.7
[[ 0.81244235  0.43976273  0.70900616  0.2865831   0.02578929]
 [ 0.89831364  0.40276155  0.78928222  0.02248522  0.60319595]
 [ 0.91513728  0.48508321  0.56947669  0.37301015  0.92306591]
 [ 0.0